export const PD_CHEQUE_STATUS = {
  PENDING: 'pending',
  DEPOSITED: 'deposited',
  REALIZED: 'realized',
  RETURNED: 'returned',
} as const;

export type PdChequeStatus =
  (typeof PD_CHEQUE_STATUS)[keyof typeof PD_CHEQUE_STATUS];

export const PD_CHEQUE_TX = {
  RECEIVE: 'PdChequeReceive',
  REALIZE: 'PdChequeRealize',
} as const;

export const ERRORS = {
  PD_CHEQUE_NOT_FOUND: 'PD_CHEQUE_NOT_FOUND',
  CHEQUE_NO_REQUIRED: 'CHEQUE_NO_REQUIRED',
  DOCUMENT_NO_REQUIRED: 'DOCUMENT_NO_REQUIRED',
  BANKING_DATE_REQUIRED: 'BANKING_DATE_REQUIRED',
  INVALID_CHEQUE_AMOUNT: 'INVALID_CHEQUE_AMOUNT',
  ALLOCATED_EXCEEDS_AMOUNT: 'ALLOCATED_EXCEEDS_AMOUNT',
  INVALID_PAYMENT_AMOUNT: 'INVALID_PAYMENT_AMOUNT',
  INVOICES_IDS_NOT_FOUND: 'INVOICES_IDS_NOT_FOUND',
  CHEQUES_ACCOUNT_MISSING: 'CHEQUES_ACCOUNT_MISSING',
  ADVANCES_ACCOUNT_MISSING: 'ADVANCES_ACCOUNT_MISSING',
  BANK_ACCOUNT_REQUIRED: 'BANK_ACCOUNT_REQUIRED',
  STATUS_NOT_ALLOWED: 'STATUS_NOT_ALLOWED',
  EDIT_ONLY_PENDING: 'EDIT_ONLY_PENDING',
};

export const CHEQUES_IN_HAND_SLUG = 'cheques-in-hand';
export const CUSTOMER_ADVANCES_SLUG = 'customer-advances';
