export const ERRORS = {
  AREA_NOT_FOUND: 'AREA_NOT_FOUND',
  AREA_NAME_EXISTS: 'AREA_NAME_EXISTS',
  AREA_CODE_EXISTS: 'AREA_CODE_EXISTS',
  AREA_HAS_ROUTE_CITIES: 'AREA_HAS_ROUTE_CITIES',
  AREA_HAS_CUSTOMERS: 'AREA_HAS_CUSTOMERS',
};
