export const ERRORS = {
  ROUTE_CITY_NOT_FOUND: 'ROUTE_CITY_NOT_FOUND',
  ROUTE_CITY_NAME_EXISTS: 'ROUTE_CITY_NAME_EXISTS',
  AREA_NOT_FOUND: 'AREA_NOT_FOUND',
  ROUTE_CITY_HAS_CUSTOMERS: 'ROUTE_CITY_HAS_CUSTOMERS',
};
