export const ERRORS = {
  AGENT_NOT_FOUND: 'AGENT_NOT_FOUND',
  AGENT_NAME_EXISTS: 'AGENT_NAME_EXISTS',
  AGENT_HAS_PAYMENTS: 'AGENT_HAS_PAYMENTS',
  UNDEPOSITED_FUNDS_NOT_FOUND: 'UNDEPOSITED_FUNDS_NOT_FOUND',
};

export const UNDEPOSITED_FUNDS_SLUG = 'undeposited-funds';
