export const ERRORS = {
  SUBCATEGORY_NOT_FOUND: 'SUBCATEGORY_NOT_FOUND',
  SUBCATEGORY_NAME_EXISTS: 'SUBCATEGORY_NAME_EXISTS',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  SUBCATEGORY_HAVE_ITEMS: 'SUBCATEGORY_HAVE_ITEMS',
};
